package cs544.jwt.security;

import org.springframework.stereotype.Service;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.io.Encoders;
import io.jsonwebtoken.security.Keys;

import javax.crypto.SecretKey;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

@Service
public class JwtUtilityService {
    // our current secret (generated by the below main method)
    private static final String SECRET = "M0g9JhdFu8bMfnkbywETmTmhtuTI+3XYBt20zQqK4w0=";
    private SecretKey key = Keys.hmacShaKeyFor(Decoders.BASE64.decode(SECRET));
    
    public static void main(String[] args) {
        // to make a new secret
        System.out.println(Encoders.BASE64.encode(Jwts.SIG.HS256.key().build().getEncoded()));
    }

    // Generate a token with the given username and roles
    public String generateToken(String username, String[] roles) {
        Map<String, Object> claims = new HashMap<>();
        claims.put("roles", roles);
        var now = Instant.now();
        return Jwts.builder()
                .claims()
                .subject(username)
                .add(claims)
                .issuedAt(Date.from(now))
                .expiration(Date.from(now.plus(24, ChronoUnit.HOURS)))
                .and()
                .signWith(key)
                .compact();
    }

    // Claims implements Map<String, Object> allowing users to easily extract the claims
    public Claims extractAllClaims(String token) {
        return Jwts.parser().verifyWith(key).build().parseSignedClaims(token).getPayload();
    }
}
